title: Aamod Save # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Deep Learning enthusiast working towards specializing in Reinforcement Learning and Computer Vision. I graduated from Arizona State University with an M.S degree in Computer Engineering. I am proficient in Python and experienced with deep learning frameworks Pytorch, Keras, and TensorFlow. I am working as a Machine Learning Engineer Volunteer at Arizona State University and a Robotics Intern at We Carpool Inc. I am curently looking for full-time opportunities in Machine Learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/aamod1996">LinkedIn</a> 
  <b href="mailto:asave@asu.edu">Email</b> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
