title: Aamod Save # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Deep Learning enthusiast working towards specializing in Reinforcement Learning and Computer Vision. I graduated from Arizona State University with an M.S degree in Computer Engineering. I am proficient in Python and experienced with deep learning frameworks Pytorch, Keras, and TensorFlow. I am working as a Machine Learning Engineer Volunteer at Arizona State University and a Robotics Intern at We Carpool Inc. If you are interested in my work you can mail me at asave@asu.edu or can connect with me on <a href="https://www.linkedin.com/in/aamod1996">LinkedIn</a>.
  
theme: jekyll-theme-slate
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
